// File generated by FlutterFire CLI, extended for web by backend_engineer (p1-001).
// Do NOT edit this file manually — re-run FlutterFire CLI or update via
// Firebase Console → Project Settings → Your Apps → SDK Config.
//
// Web values confirmed from Firebase project `redbus-3ec46`:
//   apiKey, authDomain, projectId, storageBucket, messagingSenderId — all
//   sourced from google-services.json / GoogleService-Info.plist.
//
// ⚠️  ACTION REQUIRED before going live:
//   Replace [appId] (web) with the actual web app registration ID from:
//   Firebase Console → Project Settings → General → Your Apps → Web App
//   (format: "1:319710447950:web:XXXXXXXXXXXXXXXX")
//
//   Replace [measurementId] with the Analytics stream ID from the same page
//   (format: "G-XXXXXXXXXX"). If Analytics is not enabled, remove this field.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Web (populated by p1-001) ──────────────────────────────────────────────
  // Values from Firebase project redbus-3ec46 (google-services.json +
  // GoogleService-Info.plist). appId and measurementId require web app
  // registration in Firebase Console before going live.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiwebltRgWVv7i_i5ReeoY1K3UKwwF2FU',
    authDomain: 'redbus-3ec46.firebaseapp.com',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
    messagingSenderId: '319710447950',
    // TODO(web-registration): Replace with actual web appId from Firebase Console.
    // Firebase Console → Project Settings → Your Apps → Add App → Web
    // Format: "1:319710447950:web:<hex-suffix>"
    appId: '1:319710447950:web:4552bb9d524b911ba2f61f',
    // TODO(web-registration): Replace with actual Analytics measurementId,
    // or remove if Firebase Analytics is not enabled for the web app.
    measurementId: 'G-PENDING',
  );

  // ── Android ────────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwebltRgWVv7i_i5ReeoY1K3UKwwF2FU',
    appId: '1:319710447950:android:4552bb9d524b911ba2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
  );

  // ── iOS ────────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-YvGGlTSZh1IcX9OraGn_csnPfpRlM4',
    appId: '1:319710447950:ios:5dab8f87f8ca013aa2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
    iosClientId: '319710447950-7o1oapai6u596493ehbee68t5a4l5ijk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomeet',
  );
}
