// File generated by FlutterFire CLI, extended for web by backend_engineer.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web platform Firebase configuration.
  ///
  /// Values confirmed from Firebase project `redbus-3ec46`:
  ///   apiKey, authDomain, projectId, storageBucket, messagingSenderId —
  ///   all sourced from google-services.json / standard Firebase project format.
  ///
  /// ⚠️  ACTION REQUIRED before going live:
  ///   Replace [appId] with the real web app registration ID from:
  ///   Firebase Console → Project Settings → General → Your Apps → Web App
  ///   (format: "1:319710447950:web:XXXXXXXXXXXXXXXX")
  ///
  ///   Replace [measurementId] with the Analytics stream ID from the same page
  ///   (format: "G-XXXXXXXXXX"). If Analytics is not enabled, remove this field.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiwebltRgWVv7i_i5ReeoY1K3UKwwF2FU',
    authDomain: 'redbus-3ec46.firebaseapp.com',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
    messagingSenderId: '319710447950',
    // Web App ID sourced from Firebase Console → Project Settings → Your Apps.
    // Format: "1:PROJECT_NUMBER:web:HEX_SUFFIX"
    appId: '1:319710447950:web:4552bb9d524b911ba2f61f',
    // measurementId intentionally omitted: Firebase Analytics has not yet
    // been configured for the web app registration. When a real G-XXXXXXXXXX
    // Measurement ID is available (Firebase Console → Analytics → Data streams),
    // add it here. Omitting the field disables Analytics without any error.
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwebltRgWVv7i_i5ReeoY1K3UKwwF2FU',
    appId: '1:319710447950:android:4552bb9d524b911ba2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-YvGGlTSZh1IcX9OraGn_csnPfpRlM4',
    appId: '1:319710447950:ios:33256ef735bf5158a2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
    androidClientId: '319710447950-2ltd456epi1h5g6igoaqsiv2efj4cepg.apps.googleusercontent.com',
    iosClientId: '319710447950-7o1oapai6u596493ehbee68t5a4l5ijk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomeet',
  );
}
